# ---------------------------------------------------------------
# Theme Core Configuration Settings
# See: https://theme-next.org/docs/theme-settings/
# ---------------------------------------------------------------

# If false, merge configs from `_data/next.yml` into default configuration (rewrite).
# If true, will fully override default configuration by options from `_data/next.yml` (override). Only for NexT settings.
# And if true, all config from default NexT `_config.yml` must be copied into `next.yml`. Use if you know what you are doing.
# Useful if you want to comment some options from NexT `_config.yml` by `next.yml` without editing default config.
override: true

cache:
  enable: false

# Remove unnecessary files after hexo generate.
minify: true

# Define custom file paths.
# Create your custom files in site directory `source/_data` and uncomment needed files below.
custom_file_path:
  #head: source/_data/head.njk
  #header: source/_data/header.njk
  #sidebar: source/_data/sidebar.njk
  #postMeta: source/_data/post-meta.njk
  #postBodyEnd: source/_data/post-body-end.njk
  #footer: source/_data/footer.njk
  #bodyEnd: source/_data/body-end.njk
  variable: source/_data/variables.styl
  #mixin: source/_data/mixins.styl
  style: source/_data/styles.styl

favicon:
  small: /uploads/wizard-hat-16.png
  medium: /uploads/wizard-hat-32.png
  apple_touch_icon: /uploads/wizard-hat-16.png
  safari_pinned_tab: /uploads/wizard-hat-32.png

footer:
  # Specify the date when the site was setup. If not defined, current year will be used.
  since: 2019

  # Icon between year and copyright info.
  icon:
    # Icon name in Font Awesome. See: https://fontawesome.com/icons
    name: fa fa-heartbeat
    # If you want to animate the icon, set it to true.
    animated: true
    # Change the color of icon, using Hex Code.
    color: "#ff0000"

  # If not defined, `author` from Hexo `_config.yml` will be used.
  copyright: 止息

  # Powered by Hexo & NexT
  powered: true

creative_commons:
  license: by-nc-sa
  sidebar: true
  post: false
  language:

# Schemes
# scheme: Muse
#scheme: Mist
scheme: Pisces
# scheme: Gemini

# Dark Mode
darkmode: auto

menu:
  #home: / || fa fa-home
  about: /about/ || fa fa-user
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive

# Sidebar Avatar
avatar:
  # Replace the default image and set the url here.
  url: /uploads/jinmao.webp
  # If true, the avatar will be dispalyed in circle.
  rounded: true
  # If true, the avatar will be rotated with the cursor.
  rotated: false

social:
  GitHub: https://github.com/archaeoraptor || fab fa-github
  E-Mail: mailto:zhangjk67@gmail.com || fa fa-envelope
  RSS: /atom.xml || fa fa-rss

# Blog rolls
links_settings:
  icon: fa fa-globe
  title: 友链
  # Available values: block | inline
  layout: block

links:
  uestc.icu: https://uestc.icu
  米米的博客: https://zhangshuqiao.org
  花花: https://233hsysweb.ml
  Sam's Blog: https://blog.samchu.cn


read_more_btn: false

tag_icon: true

# TagCloud settings for tags page.
tagcloud:
  # If true, font size, font color and amount of tags can be customized
  enable: true
  # All values below are same as default, change them by yourself
  min: 16 # Minimun font size in px
  max: 16 # Maxium font size in px
  start: "#ccc" # Start color (hex, rgba, hsla or color keywords)
  end: "#111" # End color (hex, rgba, hsla or color keywords)
  amount: 200 # Amount of tags, change it if you have more than 200 tags

# Custom Logo (Do not support scheme Mist)
custom_logo: #/uploads/custom-logo.jpg

github_banner:
  enable: true
  permalink: https://github.com/archaeoraptor
  title: Follow me on GitHub

font:
  enable: true

  # Uri of fonts host, e.g. https://fonts.googleapis.com (Default).
  host: https://fonts.loli.net

  # Font options:
  # `external: true` will load this font family from `host` above.
  # `family: Times New Roman`. Without any quotes.
  # `size: x.x`. Use `em` as unit. Default: 1 (16px)

  # Global font settings used for all elements inside <body>.
  global:
    external: false
    family: "Noto Serif SC"
    size:

  # Font settings for site title (.site-title).
  title:
    external: false
    family:
    size:

  # Font settings for headlines (<h1> to <h6>).
  headings:
    external: false
    family:
    size:

  # Font settings for posts (.post-body).
  posts:
    external: false
    family:

  # Font settings for <code> and code blocks.
  codes:
    external: false
    family:

disable_baidu_transformation: true

exturl: true

google_site_verification: OwUki9pTQANwT767yFIY9v_Qx4gl55MFLe3lggNnHbw

bing_site_verification: 872DC4637276109A6B54FF149DCABA8A

# Yandex Webmaster tools verification.
# See: https://webmaster.yandex.ru
yandex_site_verification: 0d554b4a05a80f0d

math:
  # Default (true) will load mathjax / katex script on demand.
  # That is it only render those page which has `mathjax: true` in Front-matter.
  # If you set it to false, it will load mathjax / katex srcipt EVERY PAGE.
  per_page: true

  # hexo-renderer-pandoc (or hexo-renderer-kramed) required for full MathJax support.
  mathjax:
    enable: false

  # hexo-renderer-markdown-it-plus (or hexo-renderer-markdown-it with markdown-it-katex plugin) required for full Katex support.
  katex:
    enable: false
    # See: https://github.com/KaTeX/KaTeX/tree/master/contrib/copy-tex
    copy_tex: false

pjax: true

mediumzoom: true

lazyload: false

# Google Analytics
google_analytics:
  tracking_id: UA-143393734-1
  # By default, NexT will load an external gtag.js script on your site.
  # If you only need the pageview feature, set the following option to true to get a better performance.
  only_pageview: false

  # Local Search
# Dependencies: https://github.com/next-theme/hexo-generator-searchdb
local_search:
  enable: true
  # If auto, trigger search by changing input.
  # If manual, trigger search by pressing enter key or search button.
  trigger: auto
  # Show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  # Unescape html strings to the readable one.
  unescape: false
  # Preload the search data when the page loads.
  preload: false

pdf:
  enable: true
  # Default height
  height: 500px

motion:
  enable: true
  async: true
  transition:
    # All available transition variants: https://theme-next.js.org/animate/
    post_block: fadeInDown
    post_header: fadeInDown
    post_body: fadeInDown
    coll_header: fadeInLeft
    # Only for Pisces | Gemini.
    sidebar: fadeInDown

vendors:
  # Available values: local, jsdelivr, unpkg
  internal: local


  # ---------------------------------------------------------------
# Comments Settings
# See: https://theme-next.js.org/docs/third-party-services/comments
# ---------------------------------------------------------------

# Multiple Comment System Support
comments:
  # Available values: tabs | buttons
  style: tabs
  # Choose a comment system to be displayed by default.
  # Available values: changyan | disqus | disqusjs | gitalk | livere | valine
  active: disqusjs
  # Setting `true` means remembering the comment system selected by the visitor.
  storage: true
  # Lazyload all comment systems.
  lazyload: false
  # Modify texts or order for any navs, here are some examples.
  nav:
    disqusjs:
     text: Load Disqus
     order: -1
    utterances:
     order: -2

# For more information: https://valine.js.org, https://github.com/xCss/Valine
# valine:
#   enable: true
#   appId: 9HDUS9zSiY41T0Vp4naCoqcC-MdYXbMMI
#   appKey: ufiyQKIMrlBkEYcA4bk1TrYj
#   placeholder: 留言可能会过一段时间才看到,急事请发邮件 # Comment box placeholder
#   avatar: mm # Gravatar style
#   meta: [nick, mail] # Custom comment header
#   pageSize: 10 # Pagination size
#   language: # Language, available values: en, zh-cn
#   visitor: false # Article reading statistic
#   comment_count: true # If false, comment count will only be displayed in post page, not in home page
#   recordIP: false # Whether to record the commenter IP
#   serverURLs: # When the custom domain name is enabled, fill it in here (it will be detected automatically by default, no need to fill in)
#   enableQQ: true # Whether to enable the Nickname box to automatically get QQ Nickname and QQ Avatar
#   requiredFields: [] # Set required fields: ['nick'] | ['nick','mail']
#   #post_meta_order: 0

# DisqusJS
# Alternative Disqus - Render comment component using Disqus API.
# Demo: https://suka.js.org/DisqusJS/
# For more information: https://github.com/SukkaW/DisqusJS
disqusjs:
  enable: true
  # API Endpoint of Disqus API (https://disqus.com/api/).
  # Leave api empty if you are able to connect to Disqus API. Otherwise you need a reverse proxy for it.
  # For example:
  # api: https://disqus.skk.moe/disqus/
  api: https://disqus.skk.moe/disqus/
  apikey: 3qJ515uApWlP58gXhzPCCk3L0NlOvrMLwt5dDITBndS8fp8She7PT1gvBdDcgwrt # Register new application from https://disqus.com/api/applications/
  shortname: arcaheoraptor # See: https://disqus.com/admin/settings/general/

# Utterances
# For more information: https://utteranc.es
utterances:
  enable: true
  repo: Archaeoraptor/archaeoraptor.github.io # Github repository name
  # Available values: pathname | url | title | og:title
  issue_term: pathname
  # Available values: github-light | github-dark | preferred-color-scheme | github-dark-orange | icy-dark | dark-blue | photon-dark | boxy-light
  theme: github-light